# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
